version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tourism_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - tourism_network

volumes:
  postgres_data:

networks:
  tourism_network:
    driver: bridge